### ISSUE TITLE
Templates cannot be deleted

### ISSUE THREAD

**Issue by mariobrostech** [v1tzor/TimePlanner#103]
Hi,

I recently started using TimePlanner, and I'm really enjoying it so far! However, I can't find a way to delete incorrectly made templates from when I was testing it out. Is this intentional, and can an option to delete templates in a future update be added?

Thanks in advance!

**Comment by v1tzor** [comment]
![Screenshot_20240131_205718_ru.aleshin.timeplanner_edit_35325370111275.jpg](https://github.com/v1tzor/TimePlanner/assets/116388544/091c957f-ca67-431e-974f-b16dbd24c286)

**Comment by mariobrostech** [comment]
Hi,

Thanks so much for your quick reply! This does seem to have fixed my issue. Is there a way that deleting templates that have already established reptitions could be implemented in a future update? I ended up having to reinstall the app just to clear these few templates out, and that doesn't make for the best UX.

Perhaps a swipe to delete gesture, a long-press on the template, or a UI element in the template editing screen itself could be added to accomplish this. Do any of those options sound doable?

Thanks again for your help!
