### ISSUE TITLE
добавить в аналитику "процент выполненных и невыполненных"

### ISSUE THREAD

**Issue by Wjxfi** [v1tzor/TimePlanner#11]
типа 36% выполнено и 64% не было сделано 

И такую статистику можно и по основным категориям сделать

Типа в "Дела" было сделано 60% и не выполнено 40% за неделю, но за месяц было выполнено 89% и не выполнено 11%, в то время как в Спорт было выполнено только 23% из 100%, не выполнено большинство, 77%, в отличии от Отдыха, где было выполнено 99% и не выполнено 1%.

конечно, это всё нужно будет переместить в график или ещё как-то, но не в словах, как я.

Изменено:

я нашел кое-что. Под словом Score на скриншоте хороший вариант. Слева будут показаны проценты (100,80,60,40,20,0), снизу день, когда эта информация была актуальна, справа сверху можно будет выбрать какой период график будет показывать (неделя,месяц,полгода,год). И, предлагаю, такой график возможно будет включить о любой из основных категорий (одной) или для всех категорий сразу или нескольких, по выбору, основных категорий.

![1cafcaa8-1ae9-4b39-bc12-85fc4296e733.jpg](https://github.com/v1tzor/TimePlanner/assets/113500363/708d0ba1-eb23-458c-b17c-3f4a34dfd873)

скриншот из https://www.f-droid.org/packages/io.github.friesi23.mhabit/

**Comment by v1tzor** [comment]
Был добавлен график статистики выполненных задач для всех категорий. Спасибо за предложение!
