### ISSUE TITLE
Для чего нужна эта кнопка? Возможно, прошу сделать её работающей

### ISSUE THREAD

**Issue by Wjxfi** [v1tzor/TimePlanner#12]
https://github.com/v1tzor/TimePlanner/assets/113500363/95f52f02-9e84-4875-bbb3-1f4ead3cf26a

**Comment by v1tzor** [comment]
Данная кнопка изменяет состояние отображения элемента добавления задачи в интервале между другими задачами. Добавьте разрыв между задачами по времени и увидьте результат😊
