### ISSUE TITLE
Leading zeros in hour/minute input fields

### ISSUE THREAD

**Issue by nvllz** [v1tzor/TimePlanner#121]
The hour/minute input fields in time and duration dialogs should show single digit values with leading zeros. It's more natural and user friendly to show 01:02 than 1:2, which is rather odd.

https://github.com/user-attachments/assets/f1432778-9b15-4b16-bfe4-a841d5b0e42c

**Comment by v1tzor** [comment]
Done!

https://github.com/user-attachments/assets/605d2f5f-3dcb-4b31-8dc8-1ad2974bf215
