### ISSUE TITLE
Future Events displayed as completed

### ISSUE THREAD

**Issue by Seestern** [v1tzor/TimePlanner#128]
I have observed the following behavior (version 1.0.0, build number 30):

(1) Let's say now it's 11/25/2024 and now it is 2:00 pm.

(2) I enter an event for the future - let's say the day in the future is 12/05/2024. The event lasts one hour and it is completely before 2:00 pm. The event is displayed as completed and finished, even though it is in the future!

(3) I enter an event for the future - let's say the day in the future is 12/05/2024. The event lasts one hour and it is completely after 2:00 pm. The event is normally displayed as still to be completed - but it is still marked as completed on the same day (11/25/2024), even though it is in the future!

**Comment by v1tzor** [comment]
Thanks, the bug has been fixed.

**Comment by topkekega** [comment]
Thank you too for the fix
