### ISSUE TITLE
Unable to set time from pm to am

### ISSUE THREAD

**Issue by 2217441** [v1tzor/TimePlanner#13]
![Screenshot_20230609-134226.png](https://github.com/v1tzor/TimePlanner/assets/116471841/40ba7718-bc86-4935-9372-32bab72f26cf)

It should be 8 hours, same with template and editor. Thanks, I've always wanted such app and now you made it available to everyone!

**Comment by v1tzor** [comment]
Thank you, your comment was taken into account in the new version of the application, the function of selecting AM and PM format in the task and template editor will be available
<img width="348" alt="TemplatesEditor" src="https://github.com/v1tzor/TimePlanner/assets/116388544/4c1a947c-1914-4013-9b56-8e4bae4bf67b">
<img width="327" alt="TimeTaskEditor" src="https://github.com/v1tzor/TimePlanner/assets/116388544/c0151809-5c69-424f-9209-b62b0be6bd5a">

**Comment by v1tzor** [comment]
Переключите формат времени в системе

**Comment by v1tzor** [comment]
Переключатель am/pm показывается только при 12 часовом формате времени

**Comment by 2217441** [comment]
Sorry, I meant to say I can't set the time from night to morning the next day and be in the statistic. like 21:00 to 05:00 without giving -16 hours error.
