### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by Mattrazol** [v1tzor/TimePlanner#2]
I think there are a couple of translations that are missing and they default to Russian.

One is in the Analytics 'Time' section, under the Total the label for the category defaults to Russian even when the language is set to English.

Same for the dialog that pops up when we are adding a subcategory. The main category, right under the title of the modal, defaults to Russian.

**Comment by v1tzor** [comment]
Thank you for finding an error in the application, I tried to fix it, in the new version this should no longer occur
