### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by SajjadKiani** [v1tzor/TimePlanner#26]
How to translate to other languages?

**Comment by v1tzor** [comment]
What language do you want to have a translation into?

**Comment by SajjadKiani** [comment]
translate to persian @v1tzor

**Comment by v1tzor** [comment]
If you want, I can add a Persian translation later in the next release.

**Comment by SajjadKiani** [comment]
of course. I can help if you want :)

**Comment by v1tzor** [comment]
OK, I'll add code optimization for this language later. I will be very grateful for your help, you can partially or completely add translations to the following files by making P.R.: [SettingsStrings](https://github.com/v1tzor/TimePlanner/blob/e2e6fd710467847ea707e814ff45faa4432c3f09/features/settings/impl/src/main/java/ru/aleshin/features/settings/impl/presentation/theme/tokens/SettingsStrings.kt), [AnalyticsStrings](https://github.com/v1tzor/TimePlanner/blob/e2e6fd710467847ea707e814ff45faa4432c3f09/features/analytics/impl/src/main/java/ru/aleshin/features/analytics/impl/presenatiton/theme/tokens/AnalyticsStrings.kt), [HomeStrings](https://github.com/v1tzor/TimePlanner/blob/e2e6fd710467847ea707e814ff45faa4432c3f09/features/home/impl/src/main/java/ru/aleshin/features/home/impl/presentation/theme/tokens/HomeStrings.kt), [EditorStings](https://github.com/v1tzor/TimePlanner/blob/e2e6fd710467847ea707e814ff45faa4432c3f09/features/editor/impl/src/main/java/ru/aleshin/features/editor/impl/presentation/theme/tokens/EditorStrings.kt)

**Comment by v1tzor** [comment]
Thank you very much for the translation! Sorry that there were problems with P.R.
