### ISSUE TITLE
Убрать несвободные зависимости

### ISSUE THREAD

**Issue by Wjxfi** [v1tzor/TimePlanner#3]
Izzyondroid показывает что в приложении есть несвободные зависимости. Я предлагаю их убрать, так как это не безопасно и отпугивает много людей, таких как я.

**Comment by v1tzor** [comment]
Несвободные зависимости были убраны

**Comment by IzzySoft** [comment]
Confirmed: GS is no longer listed. Removed NonFreeDep then, effective with the next index. Thanks for the notice, @Wjxfi!
