### ISSUE TITLE
Add recurring events

### ISSUE THREAD

**Issue by Myzel394** [v1tzor/TimePlanner#32]
Please add recurring events (weekly, monthly, etc.), this makes it much easier to set up repeating tasks.

Recurring events are a bit difficult to implement, so here are some tips:

## Define absolute and relative recurring events
* Absolute recurring events are bound to a specific date, like the 20th of the month, every Tuesday, etc.
* Relative recurring events are bound to relative dates, like every third Monday, last Sunday in month, etc.
* Allow the user to select multiple weekdays, if a weekly recurring event is selected

**Comment by v1tzor** [comment]
Great idea for improvement, it will be added soon :D

**Comment by v1tzor** [comment]
[New app verison](https://github.com/v1tzor/TimePlanner/releases/tag/0.6.0) :)

**Comment by Myzel394** [comment]
Where can you add recurring events? I can not find anything related to this
