### ISSUE TITLE
"Broadcast task" switch (on/off) within each template

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#36]
Please adding a switch within each template to make "live" a task in the planner (without having to repeat this action every day).

![1000040426](https://github.com/v1tzor/TimePlanner/assets/113377431/e2349633-c59f-4128-85dd-d8c48fc96f13)

![1000040428](https://github.com/v1tzor/TimePlanner/assets/113377431/33c6fcd7-d764-4fcc-8e2f-05e6fe659582)

**Comment by v1tzor** [comment]
Do you mean automatic repeat? This feature is already implemented in the application after you create a template, or what do you mean by a "live" task

**Comment by v1tzor** [comment]
That is, schedules should be automatically created for a templated task, so as not to create them manually afterwards?

**Comment by v1tzor** [comment]
> > That is, schedules should be automatically created for a templated task, so as not to create them manually afterwards? Right?
> 
> Right, but your app doesn’t show them until I press "Plan now". Also having a template ready not necessarily means that I want to use it; for this I need the switch on/off.

I will try to implement

**Comment by v1tzor** [comment]
Manually means you need to click on "Plan now" to create a schedule and a task in it

**Comment by v1tzor** [comment]
Or do you mean in general to create a switch to disable a similar task with repetition

**Comment by v1tzor** [comment]
> Или вы имеете в виду вообще создать переключатель для отключения подобной задачи с повторением

For example, there is a template that repeats once a week and when the switch is turned on, schedules are automatically created for it, and when it is turned off, it is inactive. Right?

**Comment by v1tzor** [comment]
> To avoid unexpected behaviors of the app, "broadcast ON" will fill the planner for a maximum of one hundred days (ahead) the current date (recurring events).
> 
> 
> 
> This will prevent the app from filling the calendar for the eternity.
> 
> 
> 
> Does the app need a refresh button (somewhere) to calculate new commitments every day or do you have a trick to make it updated automatically?
> 
> 
> 
> In any case, a manual refresh button might be useful (to force the creation of new commitments if scheduled).
> 
> 
> 
> What do you think about it?

When the template is active, the application creates notifications at the right time sequentially, that is, when you receive a notification, the next one is already created. In turn, tasks along with the schedule are created when the user presses on a certain date, this method avoids unnecessary overflows

**Comment by v1tzor** [comment]
> If I have a daily recurring event, what would the behavior of the app be if first I enable "broadcast" (ON) then disable it (OFF)?
> 
> 
> 
> Does the app delete scheduled all occurrences previously created or just stop creating the new ones?
> 
> 
> 
> Actually, we should be in control over both things.  

If you disable the template, then subsequent scheduling will not occur, and template tasks that were created in advance will be deleted. The next time they are enabled, they will be re-added if they do not conflict with other tasks.

**Comment by v1tzor** [comment]
I hope to release a new version of the application today

**Comment by v1tzor** [comment]
The application is already ready, I am now completing preliminary testing and will be releasing a new version already. If you suddenly notice any bugs in the application, please let us know

**Comment by v1tzor** [comment]
Yes, on github in the near future, I will write to you when it will be possible to download

**Comment by v1tzor** [comment]
> Is it compatible with the fdroid one? Or I have to unistall before the fdroid one in order to install the Github one?
> 
> I prefer the fdroid way (in normal situation).

Yes, it is compatible, just a new version of the application will appear on the fdroid only after a certain time when the service updates the data. The apk file is the same in both cases

**Comment by v1tzor** [comment]
Ready! https://github.com/v1tzor/TimePlanner/releases/tag/0.7.0

**Comment by v1tzor** [comment]
> Might you extend (in next version) the "remember the choice made" to Analytics too?
> 
> ![1000040503](https://user-images.githubusercontent.com/113377431/268458136-4f884349-99b3-4f76-9f25-e4f5ef8fda8e.jpg)

Yes, it will be possible to do. 

I tried to make categories of text in 2 lines, but it turns out not very nice, + due to some limitations of the system design, if there are a lot of such elements, then the graph does not expand, so I had to leave it as it is, sorry

**Comment by v1tzor** [comment]
> Please add a regular XEC address I send a new donation (too much happy for this update).

Okey, just a second, thank you very much

**Comment by v1tzor** [comment]
![image](https://github.com/v1tzor/TimePlanner/assets/116388544/ed2a2217-e9e3-41b4-b21b-71c5bf349941)

Right?

**Comment by v1tzor** [comment]
> Extreme solution. What do you think?
> 
> ![1000040506](https://user-images.githubusercontent.com/113377431/268458509-8b25e37f-b598-4f14-8541-2afb28e1a10d.jpg)

It will be possible to try

**Comment by v1tzor** [comment]
> ![image](https://github.com/v1tzor/TimePlanner/assets/116388544/ed2a2217-e9e3-41b4-b21b-71c5bf349941)
> 
> Right?

XEC(BEP20): 0x4cAfa6De0D1968cA8C2a7aB06CE28d0A1aD2C7b9

**Comment by v1tzor** [comment]
> No. Install Unstoppable Wallet. Trust Wallet doesn't have the native XEC blockchain.
> 
> Just an example of eCash (XEC) native address:
> 
> ecash:qp3v6hy74n9u4nsmt5w37wqav92p5ux6dus06ay3ae
> 
> The ecash: handle is mandatory!

Okay, I'll try it now

**Comment by v1tzor** [comment]
ecash: qpvd6q2rzt52k4flx4ux90uwnp8cd6na2ql06w6jzz

**Comment by v1tzor** [comment]
> ecash: qpvd6q2rzt52k4flx4ux90uwnp8cd6na2ql06w6jzz

This is from the app: Unstoppable - Bitcoin & Crypto Wallet

**Comment by v1tzor** [comment]
Sorry

ecash:qqc0k95nfhkseel9p4avz5jwk6s4vum7rceegten5x

**Comment by v1tzor** [comment]
![image](https://github.com/v1tzor/TimePlanner/assets/116388544/3b1d91ed-eb6f-4869-a22f-4f2cb02460f1)

**Comment by v1tzor** [comment]
![image](https://github.com/v1tzor/TimePlanner/assets/116388544/4668a0b5-8116-4c56-8304-8702ba1a4997)

**Comment by v1tzor** [comment]
It seems to have come. But how is this possible, I copied the address from the same place 2 times

**Comment by v1tzor** [comment]
> ![image](https://user-images.githubusercontent.com/116388544/268459522-4668a0b5-8116-4c56-8304-8702ba1a4997.png)

Thank you very much!

**Comment by v1tzor** [comment]
> > It seems to have come. But how is this possible, I copied the address from the same place 2 times
> 
> Because the Bitcoin-like coins have multiple addresses (this is a mathematical trick I guess). I am not sure.

Okay, I get it. It's just that I'm new to the field of cryptocurrencies and therefore still understand all this

**Comment by v1tzor** [comment]
The transaction is over, everything is fine!

**Comment by v1tzor** [comment]
The transfer has arrived

**Comment by v1tzor** [comment]
![image](https://github.com/v1tzor/TimePlanner/assets/116388544/c3b07778-c4ae-42b9-a5c2-1dcd7b7a3488)
