### ISSUE TITLE
Some visual issues

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#37]
OnePlus CPH2399
Android 13
TimePlanner 0.6.3 (f-droid)

![1000040432](https://github.com/v1tzor/TimePlanner/assets/113377431/658fda93-b5c7-4430-8d73-e4e0f370bd0d)

**Comment by v1tzor** [comment]
> I think this bug is because I have a big font in a small screen (smartphone).

I removed the size restriction of this element, it seems to work

**Comment by v1tzor** [comment]
The bug has been fixed. I checked everything is fine on different fonts. If you suddenly have a problem, write
