### ISSUE TITLE
Please adding an 'About' section within the app

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#38]
A section within the app with all the info about the app (version, build, installation channel, developer, etc.)

**Comment by v1tzor** [comment]
Everything will be added soon

**Comment by v1tzor** [comment]
> Please add also the Github issues url (in About section).

![Screenshot_20230914_235922_ru.aleshin.timeplanner_edit_264295042369044.jpg](https://github.com/v1tzor/TimePlanner/assets/116388544/31675c45-eecb-4848-bbbf-de39afb93563)

![Screenshot_20230914_235930_ru.aleshin.timeplanner_edit_264276846354984.jpg](https://github.com/v1tzor/TimePlanner/assets/116388544/24b351f1-ea14-404d-9583-6e5d9628bd4d)

The section was originally added, wait for the new release

**Comment by v1tzor** [comment]
> How fast you are! Crazy development speed. Hey dev, take a pause! 😊

Thank you)) good 😁
