### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#39]
Please add direct cryptocurrency addresses within the app. I don't want going around to websites.

TRX, LTC, BTC, XEC, SOL, BCH, ALGO, XTZ, DASH, XMR addresses available for donations.

**Comment by v1tzor** [comment]
Donat added! I think I did everything right :)

**Comment by v1tzor** [comment]
I will try to add everything

**Comment by v1tzor** [comment]
> Give me your TRX or XEC address I send you a small donation now. Let's try.

Sorry, I just saw it now. I will be very grateful to you) Thank you very much!
TRX: TKC3NsKSS9hJRvofeJKceT5wC2bqTkPRUE
XEX(BEP20): 0x4cAfa6De0D1968cA8C2a7aB06CE28d0A1aD2C7b9

**Comment by v1tzor** [comment]
I use trust wallet and when choosing TRX it says: "Tron(TRX)"

**Comment by v1tzor** [comment]
Ohh i found

**Comment by v1tzor** [comment]
Second

**Comment by v1tzor** [comment]
> Give me your TRX or XEC address I send you a small donation now. Let's try.

TRON(BEP20): 0x4cAfa6De0D1968cA8C2a7aB06CE28d0A1aD2C7b9

**Comment by v1tzor** [comment]
![image](https://github.com/v1tzor/TimePlanner/assets/116388544/87ebf730-5cf2-4656-b03a-9e1ad7738174)

Right?

**Comment by v1tzor** [comment]
![image](https://github.com/v1tzor/TimePlanner/assets/116388544/744aa723-b49f-4e6c-b0b7-ec878f1e944b)

Yes! Thanks you very much❤️

**Comment by v1tzor** [comment]
Thank you again for your support! I am insanely pleased)

**Comment by v1tzor** [comment]
> Stanislav, write the crypto addresses in the "Code" section of this Github too. Somewhere.

![image](https://github.com/v1tzor/TimePlanner/assets/116388544/bc4ab175-69bb-42e0-bdc1-ba45f1d453b2)

The readme contains the addresses

**Comment by v1tzor** [comment]
> Last hint, I promise. If you can, open a page account to Time Planner in Mastodon social network. Because it brings new supporters.

Good)

**Comment by v1tzor** [comment]
> I didn’t really have much because I paid for my Netflix subscription two weeks ago, and I haven’t ordered cryptocurrencies since.
> 
> In the coming weeks I will make a new order and hope to be able to send more.
> 
> The important thing is that you are now ready to receive support for your great work.

❤️‍🔥

**Comment by v1tzor** [comment]
Now I am creating a completely new application with even more improvements and inter-user interaction with the backend! I hope to release a test release soon) I'm still a little late because of my studies, but I hope that I will succeed! Your support helps me a lot)

**Comment by v1tzor** [comment]
> I use Unstoppable Wallet. It has the native blockchain for XEC. Not 0x...
> 
> You can find it on F-droid. It is full open source.
> 
> https://www.f-droid.org/packages/io.horizontalsystems.bankwallet/

Well I'll keep in mind

**Comment by v1tzor** [comment]
> I discovered that BTCB wants BNB tokens to perform a transaction (fees).
> 
> So better you add directly the BNB one. I hope it is an UW bug, but I feel it is not. I opened an issue about it in UW side.

Done

**Comment by v1tzor** [comment]
![image](https://github.com/v1tzor/TimePlanner/assets/116388544/a3679f73-25b6-4b52-9288-9b94227d5c16)

**Comment by v1tzor** [comment]
> Just tried one minute ago with a micro payment to test your BNB Smart Chain address.
> 
> 
> 
> High speed transactions. Low fees. I leaved BTCB because it requires BNB as network fees in order to send founds. Doesn't make sense.

Okay, everything matches
