### ISSUE TITLE
Some improvements in "Categories"

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#40]
Might you add "Health" category and renaming "Hygiene" in "Personal Care"? I mean by default.

Do you agree?

In Health I added "Dentist" as sub-category.
In Personal Care "Hairdresser" (for example).

**Comment by v1tzor** [comment]
> Might you add "Health" category and renaming "Hygiene" in "Personal Care"? I mean by default.
> 
> Do you agree?
> 
> In Health I added "Dentist" as sub-category. In Personal Care "Hairdresser" (for example).

Yes, I think it would really be more correct. I'll change that

**Comment by v1tzor** [comment]
Мне тоже было приятно познакомиться :) Спокойной ночи, до скорого :D

**Comment by v1tzor** [comment]
> Might you add also Shopping as main category? Or is it better to include in Other?
> 
> Maybe Other can be renamed "Miscellaneous" to indicate things not particularly important but notable to write in planner/statistics.
> 
> I wait your opinion about it.

OK, I think it's better to add a new category with purchases. As for the "other" category, it is really quite appropriate to rename it, then I will do it soon

**Comment by v1tzor** [comment]
The categories were renamed:
- "Other" to "Miscellaneous"
- "Hygiene" to "Personal Care"
Added:
- Health
- Shopping

When installing a new version, your database will be updated and synchronized!

**Comment by v1tzor** [comment]
I can change the limit of the number of lines of the category text to 2

**Comment by v1tzor** [comment]
> Maybe "Miscellaneous" won’t get the second line. Can you try?
> 
> ![1000040466](https://user-images.githubusercontent.com/113377431/268350318-44627ccb-234c-4c0e-a83c-1c9233e466b4.jpg)

I will try to solve this problem until I can answer for sure
