### ISSUE TITLE
Day turning bar moved to the bottom

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#41]
It is just a consideration. Not a request.
What do you think about it?
Is it an unnecessary work?
Your opinion, dev.

It is for thumbs comfort.

![1000040454](https://github.com/v1tzor/TimePlanner/assets/113377431/2d2017b3-a5d1-4a7a-b9d4-9705cf2e5c5d)

**Comment by v1tzor** [comment]
> It is just a consideration. Not a request.
> 
> What do you think about it?
> 
> Is it an unnecessary work?
> 
> Your opinion, dev.
> 
> 
> 
> It is for thumbs comfort.
> 
> 
> 
> 
> 
> ![1000040454](https://github.com/v1tzor/TimePlanner/assets/113377431/2d2017b3-a5d1-4a7a-b9d4-9705cf2e5c5d)
> 
> 

I'll think about this offer, I'm not at home yet, so I can't say for sure

**Comment by v1tzor** [comment]
I think it's better to leave the user interface as it is for a better visual experience. Regarding the volume keys, it is better not to use them to interact with a specific UI of the application
