### ISSUE TITLE
Remember the last choice made (free time boxes)

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#42]
I really like the calculation of free time between the commitments.

Unfortunately I have to enable it every time I launch the app again.

![1000040457](https://github.com/v1tzor/TimePlanner/assets/113377431/fff1cfd7-fb3a-47ec-8a1d-1c7751242992)

**Comment by v1tzor** [comment]
Готово! В новом релизе настройки отображения задач будут сохраняться
