### ISSUE TITLE
[Solved] "Delete all data" button doesn't clear all data

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#43]
This is the situation after "delete all data" action.
I would an atomic bomb. Factory reset of the app.

![1000040494](https://github.com/v1tzor/TimePlanner/assets/113377431/61965599-0863-4f47-ad73-73e63fe6e55e)

![1000040492](https://github.com/v1tzor/TimePlanner/assets/113377431/2f35d473-844f-4514-b58e-59681ebe983b)

**Comment by v1tzor** [comment]
Since analytics does not have a dynamic update, after deleting all the data, you need to "refresh" the screen or even re-enter the application. Have you done this?

**Comment by v1tzor** [comment]
> Могу ли я закрыть эту проблему как решенную? Никакого плохого поведения приложения, верно?

Yes, no problem)
