### ISSUE TITLE
Recurring events: the broadcast button schedules for the eternity!

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#44]
![1000040515](https://github.com/v1tzor/TimePlanner/assets/113377431/5dd34374-88cb-461a-bd44-081057ef8e1e)

**Comment by v1tzor** [comment]
When you select a date that fits the conditions of repetition, it is automatically filled with tasks. Make a restriction?

**Comment by v1tzor** [comment]
By the way, if you want to delete all the data now, it's better to stop all recurring tasks. Auto-stop will appear in the next version

**Comment by v1tzor** [comment]
Look, the data is not filled in immediately for a year or 2 ahead, they are created when you click on the desired date. Notifications, in turn, just follow each other until you leave them

**Comment by v1tzor** [comment]
So, it is possible to programmatically limit all this. For example: if the difference between the current date and the selected date is a year, then do not create a schedule for this task

**Comment by v1tzor** [comment]
Make a year limit?

**Comment by v1tzor** [comment]
100 days or 100 schedules?

**Comment by v1tzor** [comment]
> I think 100 schedules. What do you say?

I think that restrictions using this algorithm can be imposed for a long period of time, because in fact there is not much difference with the restriction, since the database is not filled.

Regarding 100 schedules, counting the number of existing schedules with added tasks or the tasks themselves when choosing a date does not seem to me to be a very good practice

**Comment by v1tzor** [comment]
> Theorycally it is better 100 days, but no one task happen more than one time a day...

I agree with you

**Comment by v1tzor** [comment]
The best thing in this situation seems to me to still do a check for 100 days, since in fact we cannot do more than 100 lists during this time

**Comment by v1tzor** [comment]
> The best thing in this situation seems to me to still do a check for 100 days, since in fact we cannot do more than 100 lists during this time

Then I'll do it :D

**Comment by v1tzor** [comment]
Completed! I also removed the automatic creation of tasks if you move back, because actually enabling the template now does not guarantee that it was enabled in the past and was executed.

**Comment by v1tzor** [comment]
> Excuse me, where has been placed the delete button of a template? I cannot find it... I want kill one template but it seems immortal. 😅

You need to cancel the repetitions on the selected days, then the template deletion will open
