### ISSUE TITLE
Yet graphical issues in my UI (Analytics)

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#45]
The proper one is on my mother phone:

• Moto e32(s)
• Android 12
• TP 0.7.2

![1000040561](https://github.com/v1tzor/TimePlanner/assets/113377431/31ec20f6-38c2-4344-943e-80aa4b724757)

The improper one is on my phone:

• OnePlus CPH2399
• Android 13
• TP 0.7.2

![1000040563](https://github.com/v1tzor/TimePlanner/assets/113377431/df72e322-93f5-4f9d-945a-764c693561fc)

**Comment by v1tzor** [comment]
I think that at the moment it is possible to make the name expand to 2 lines when a certain category is selected. Or will have to globally change the UI of all analytics, which is difficult

**Comment by v1tzor** [comment]
Let me then release a small patch with a small change and then close

**Comment by v1tzor** [comment]
Adapted the analytics UI. I also added animations to some places
