### ISSUE TITLE
Adding a notes' field within the editor, visible in planner view

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#47]
Hi Stan! I mean just a small note, a hint, even 30 characters. 
For example: "Go to work at 9:00".

![1000042020](https://github.com/v1tzor/TimePlanner/assets/113377431/adda8762-5299-4bdc-a95e-3ce8d9e869f7)

![1000042022](https://github.com/v1tzor/TimePlanner/assets/113377431/29796d6f-a963-4ce0-bc8c-e3fd940cf57f)

**Comment by v1tzor** [comment]
Okay, so you want me to add a field for manually entering a note and + displaying it? Just clarifying

**Comment by v1tzor** [comment]
I'll try to add

**Comment by v1tzor** [comment]
I added notes, this is a really cool improvement, I will try to release a release soon

**Comment by v1tzor** [comment]
> I added notes, this is a really cool improvement, I will try to release a release soon

![Screenshot_20231005_001503_ru.aleshin.timeplanner.jpg](https://github.com/v1tzor/TimePlanner/assets/116388544/484c9646-ebde-4447-ab81-6728b46fa7aa)

![Screenshot_20231005_001458_ru.aleshin.timeplanner.jpg](https://github.com/v1tzor/TimePlanner/assets/116388544/dd7550aa-ca6a-4738-b6bb-602c66161946)

Test version. Also when you click on a note, it will expand with animation

**Comment by v1tzor** [comment]
The new version is already available!

**Comment by v1tzor** [comment]
After writing a note, you need to click on the check mark on the right so that it applies

**Comment by v1tzor** [comment]
Also, if the task is completed, the note display is disabled for it

**Comment by v1tzor** [comment]
> What is the characters limit? 30?

Length: 160; Max lines: 1(compact view)/4(extended view)

**Comment by v1tzor** [comment]
> > Also, if the task is completed, the note display is disabled for it
> 
> You mean, the event is not repeated again?

Just the note stops showing if the task is completed. If you set the time for the task to be active again, it will start showing

**Comment by v1tzor** [comment]
> Just noticed that in template editor, the field "note" lacks. I hope this can be implemented in future updates.

Yes, I didn't add notes to the templates. Since in fact a note is a one-time event
