### ISSUE TITLE
Small notes do not get saved

### ISSUE THREAD

**Issue by xfarrow** [v1tzor/TimePlanner#52]
Whenever I write a note within an event and click on "save", said note is not kept saved. 

![Screenshot_2023-10-07-18-06-33-576_ru aleshin timeplanner](https://github.com/v1tzor/TimePlanner/assets/49845537/377265ca-66e0-40ed-860b-9bdec4cf36e4)
![Screenshot_2023-10-07-18-06-38-923_ru aleshin timeplanner](https://github.com/v1tzor/TimePlanner/assets/49845537/4116c755-7d9d-4260-a3d9-fff11260a85f)

**Comment by v1tzor** [comment]
> Whenever I write a note within an event and click on "save", said note is not kept saved.
> 
> ![Screenshot_2023-10-07-18-06-33-576_ru aleshin timeplanner](https://user-images.githubusercontent.com/49845537/273396410-377265ca-66e0-40ed-860b-9bdec4cf36e4.jpg) ![Screenshot_2023-10-07-18-06-38-923_ru aleshin timeplanner](https://user-images.githubusercontent.com/49845537/273396413-4116c755-7d9d-4260-a3d9-fff11260a85f.jpg)

You need to click on the check mark after you enter the text of the note. This is a temporary solution, this problem will be fixed soon.

**Comment by v1tzor** [comment]
A change was made to the [previous release](https://github.com/v1tzor/TimePlanner/releases/tag/0.7.6). Try installing it again  :D

**Comment by xfarrow** [comment]
Oh thank you for your amazing work
