### ISSUE TITLE
Strange behavior when there is an event ending at 23:59

### ISSUE THREAD

**Issue by xfarrow** [v1tzor/TimePlanner#53]
If I create an event which ends at 23:59, the app will tell me there's 1 minute of free time. If I create another event here (23:59 to 23:59), the app will tell me the same, essentially never ending.
Thank you for your patience.

The version is `0.7.6` build 22

![IMG_20231009_084710](https://github.com/v1tzor/TimePlanner/assets/49845537/4c66ee9a-b953-426d-94da-515d2fb8908a)

**Comment by v1tzor** [comment]
The inscription with free time has been corrected. This change will be available in the next release
