### ISSUE TITLE
[Feature Request] one click weekly plan

### ISSUE THREAD

**Issue by iamtalhaasghar** [v1tzor/TimePlanner#54]
It would be nice if we can apply a template to all days of current week instead of applying it to just today. 

For example: A person does an excercise daily from 7am to 8am. He will have to manually apply template / create task for each day separately. Wouldn't it be nice if we can have a setting while creating template to specify whether it should apply for whole week or just today. Will save some manuall effort.

Thanks for such a nice app. 

Lots of 💝 from 🇵🇰

**Comment by v1tzor** [comment]
> It would be nice if we can apply a template to all days of current week instead of applying it to just today.
> 
> For example: A person does an excercise daily from 7am to 8am. He will have to manually apply template / create task for each day separately. Wouldn't it be nice if we can have a setting while creating template to specify whether it should apply for whole week or just today. Will save some manuall effort.
> 
> Thanks for such a nice app.
> 
> Lots of 💝 from 🇵🇰

Thank you for your assessment :). The application already has the ability to make the template repetitive, for this you need:
1) Go to the template screen
2) Select the desired template and click on the repeat button
3) In the menu that appears, select the repetition rate
4) Click on the "Start" button in the template

(I hope I understood you correctly, if suddenly not, correct me)

<img width="340" alt="Снимок экрана 2023-10-11 в 20 43 11" src="https://github.com/v1tzor/TimePlanner/assets/116388544/cc7fdd38-95be-42ed-ba5c-937e70a64c1d">
<img width="350" alt="Снимок экрана 2023-10-11 в 20 45 00" src="https://github.com/v1tzor/TimePlanner/assets/116388544/6fb39bf4-9127-45d3-8651-816849f6028e">
<img width="350" alt="Снимок экрана 2023-10-11 в 20 45 22" src="https://github.com/v1tzor/TimePlanner/assets/116388544/242071b5-d812-4a51-8b3b-cd94841daa74">

**Comment by iamtalhaasghar** [comment]
Thanks! Yes thats what i was looking for. I missed that icon somehow. Again thanks for pointing this out.

I have been using this app since the start of this week and my productivity is going up day by day.
