### ISSUE TITLE
All categories editable

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#55]
I would like to edit each category to have the ability to heavily customizing my planner.

What do you think, Stan? Is it feasible?

**Comment by v1tzor** [comment]
> I would like to edit each category to have the ability to heavily customizing my planner.
> 
> What do you think, Stan? Is it feasible?

Yes, it is possible to do this. In the next update I will add

**Comment by travisfw** [comment]
How do I edit the categories? I am a parent, and childcare is conspicuously missing, considering it occupies most of my time.
