### ISSUE TITLE
Some changes to crypto donation icon

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#56]
My proposal is changing the arrow with a more intuitive icon.

Because "support the application" brings on the web and the arrow doesn't hint crypto addresses by itself. In my opinion.

![1000092955](https://github.com/v1tzor/TimePlanner/assets/113377431/4ed5d69b-c54d-412e-921e-195f700267bf)

![4806878](https://github.com/v1tzor/TimePlanner/assets/113377431/98a3253c-0a7f-4bf3-8bc4-acf7c0af8bb4)

**Comment by v1tzor** [comment]
> Also a bigger button for crypto donations. It not seems enough visible in my opinion (crypto button I mean).
> 
> What is your position about it?

I think you can make one button that will open crypto addresses so that everything is intuitive

**Comment by v1tzor** [comment]
Done!
![Screenshot_20231013_185639_ru.aleshin.timeplanner.jpg](https://github.com/v1tzor/TimePlanner/assets/116388544/423da137-da06-4ef8-9b98-fc2aba8be8d2)
