### ISSUE TITLE
Restore action doesn't run properly

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#57]
Impossible installing a backup. "Contact developer" toast bar always appears.

TP 0.7.6 (fdroid)
Android 13
OnePlus CPH2399

![1000092973](https://github.com/v1tzor/TimePlanner/assets/113377431/b4830627-d8cf-4632-b215-3e6de60f7980)

**Comment by v1tzor** [comment]
> Impossible installing a backup. "Contact developer" toast bar always appears.
> 
> TP 0.7.6 (fdroid) Android 13 OnePlus CPH2399
> 
> ![1000092973](https://user-images.githubusercontent.com/113377431/274499814-b4830627-d8cf-4632-b215-3e6de60f7980.jpg)

I found an error. The library that was responsible for converting data to files and back for some reason stopped working correctly after updating versions of other libraries. Therefore, I was forced to switch to a more powerful and reliable library with which such problems should no longer occur. 

Unfortunately, the previous backups will be invalid :(. 
If you still want to recover the lost data, please write, then I will leave you an email address, you will send me a backup file, and then I will try to manually change the structure of your backup file and send a working version to you.

**Comment by v1tzor** [comment]
> I deleted all the app data and created a new backup after adding some templates.
> 
> 
> 
> Do you want to laugh?
> 
> 
> 
> I get the notification of the match Italy - Malta belonging to the old backup.
> 
> 
> 
> Are there the ghosts?

It looks like it.. I'll release a patch and fix it soon. I'm sorry

**Comment by Pranit-DC** [comment]
I am facing same bug, not able to restore backup file which contains some templates. I have saved backup file and it got saved as zip file so I extracted it, it is a json file. While restoring there no option to select that json file and when I select ZIP file it gives pop-up saying error occurred contact developer. What should I do? 
![Uploading Screenshot_20241210-205921_TimePlanner.jpg…]()
