### ISSUE TITLE
createdAt date

### ISSUE THREAD

**Issue by MaximilianGaedig** [v1tzor/TimePlanner#58]
Is there a createdAt date stored? Even if it's not displayed, it would be important for me to have that in the future when i want to analyze the data.

Also, thank you very much for this amazing app!

**Comment by v1tzor** [comment]
> Is there a createdAt date stored? Even if it's not displayed, it would be important for me to have that in the future when i want to analyze the data.
> 
> Also, thank you very much for this amazing app!

Thank you. Which one do you mean: Task (in the schedule), Schedule (day), Template, Category?

**Comment by MaximilianGaedig** [comment]
You can't ever have too much data when the volume is this low right? But the most important is task in the schedule

**Comment by v1tzor** [comment]
> Is there a createdAt date stored? Even if it's not displayed, it would be important for me to have that in the future when i want to analyze the data.
> 
> Also, thank you very much for this amazing app!

So far, the date of creation of the task is not stored at the moment

**Comment by MaximilianGaedig** [comment]
Oh is it something you are planning to add? It is useful to see if the task has been added after, during or before to see if it was planned

**Comment by v1tzor** [comment]
Done! A new release will be available soon :D

![planning](https://github.com/v1tzor/TimePlanner/assets/116388544/cbf6e185-847f-4458-bf4d-f182b7d48222)
