### ISSUE TITLE
New behavior for calendar button

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#59]
I find more productive a long press to go in the current day and tap once to show month calendar view.

Let me know what is your opinion about this.

Perhaps it would require a switch that reverses behavior according to the user’s preference?

**Comment by v1tzor** [comment]
> I find more productive a long press to go in the current day and tap once to show month calendar view.
> 
> 
> 
> Let me know what is your opinion about this.
> 
> 
> 
> Perhaps it would require a switch that reverses behavior according to the user’s preference?

I think it's really possible to add a switch to the settings to control the expected reaction of the button
