### ISSUE TITLE
[Privacy] Screen protection over "recent apps" and "screenshot"

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#60]
Some apps give the ability (optional) to switch ON/OFF the "screenshot" and "recent apps" protection feature by other prying apps.
Basically a privacy feature. Here an implementation and some examples.

![271815693-2e7d379a-c81c-41b1-88d2-7170fc429af7](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/8177e581-55ce-4aab-b2ed-41fb7fc3c1d8)

![1000042037](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/de821f85-2361-437f-95be-fc2a4783ff54)

![1000042036](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/499a76af-6db7-4f6b-b886-f06ff7dad708)

**Comment by v1tzor** [comment]
> Some apps give the ability (optional) to switch ON/OFF the "screenshot" and "recent apps" protection feature by other prying apps.
> 
> Basically a privacy feature. Here an implementation and some examples.
> 
> 
> 
> 
> 
> ![271815693-2e7d379a-c81c-41b1-88d2-7170fc429af7](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/8177e581-55ce-4aab-b2ed-41fb7fc3c1d8)
> 
> 
> 
> ![1000042037](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/de821f85-2361-437f-95be-fc2a4783ff54)
> 
> 
> 
> ![1000042036](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/499a76af-6db7-4f6b-b886-f06ff7dad708)
> 
> 

I think it's a good idea to improve! In the next release it will be added :D

**Comment by v1tzor** [comment]
Done!
 https://github.com/v1tzor/TimePlanner/assets/116388544/78f8b9da-bb6c-40a0-baa5-ec3706f8556c

**Comment by v1tzor** [comment]
Done! [Video](https://i.imgur.com/RKCA3Ii.mp4)

**Comment by v1tzor** [comment]
> Might you adding AVAX and FTM in next update? You can find both in UW.

OK, I'll add
