### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by groeable** [v1tzor/TimePlanner#62]
Can I help with translation to Polish?

**Comment by v1tzor** [comment]
Yes, of course! To do this, you need to make a fork of the project and add variables with translation to the following files: [HomeStrings](https://github.com/v1tzor/TimePlanner/blob/main/features/home/impl/src/main/java/ru/aleshin/features/home/impl/presentation/theme/tokens/HomeStrings.kt#L24C8-L24C8), [AnalyticsStrings](https://github.com/v1tzor/TimePlanner/blob/main/features/analytics/impl/src/main/java/ru/aleshin/features/analytics/impl/presenatiton/theme/tokens/AnalyticsStrings.kt), [EditorStrings](https://github.com/v1tzor/TimePlanner/blob/main/features/editor/impl/src/main/java/ru/aleshin/features/editor/impl/presentation/theme/tokens/EditorStrings.kt), [SettingsStrings](https://github.com/v1tzor/TimePlanner/blob/main/features/settings/impl/src/main/java/ru/aleshin/features/settings/impl/presentation/theme/tokens/SettingsStrings.kt), [TimePlannerStrings](https://github.com/v1tzor/TimePlanner/blob/main/core/ui/src/main/java/ru/aleshin/core/ui/theme/tokens/TimePlannerStrings.kt). Next, you will need to make a pull request. So, if you want, you can translate, I will be very grateful to you :D. Either I can translate with the help of a translator
