### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by SirCrownguard** [v1tzor/TimePlanner#63]
Hey,

I saw that the translation topic was opened before this one. I downloaded the files you shared there, but this is the first time I am translating from a file with a .kt extension. How should I do it?

**Comment by v1tzor** [comment]
> Hey,
> 
> 
> 
> I saw that the translation topic was opened before this one. I downloaded the files you shared there, but this is the first time I am translating from a file with a .kt extension. How should I do it?

Did you make a fork project in the Android studio? Because only with the fork you can later make a pull request with change. If you are not a developer, I can add a translation for you by means of an interpreter

**Comment by SirCrownguard** [comment]
> Did you make a fork project in the Android studio? Because only with the fork you can later make a pull request with change. If you are not a developer, I can add a translation for you by means of an interpreter

That would be good. Yes, I'm not a developer. I just download the strings files of some of the open source applications I like and translate them into Turkish. Since I liked your application, I wanted to translate it into Turkish.

**Comment by v1tzor** [comment]
>  > Did you make a fork project in the Android studio? Because only with the fork you can later make a pull request with change. If you are not a developer, I can add a translation for you by means of an interpreter
> 
> 
> 
> That would be good. Yes, I'm not a developer. I just download the strings files of some of the open source applications I like and translate them into Turkish. Since I liked your application, I wanted to translate it into Turkish.

OK, thanks, then if so you can send the files either to the mail dev.aleshin@gmail.com or to google drive (then send the link)❤️

**Comment by SirCrownguard** [comment]
I'm sorry, I didn't get. Which files should I send you? Because I don't have any files. How can I help for translation?

**Comment by v1tzor** [comment]
[HomeStrings](https://github.com/v1tzor/TimePlanner/blob/main/features/home/impl/src/main/java/ru/aleshin/features/home/impl/presentation/theme/tokens/HomeStrings.kt#L24C8-L24C8), [AnalyticsStrings](https://github.com/v1tzor/TimePlanner/blob/main/features/analytics/impl/src/main/java/ru/aleshin/features/analytics/impl/presenatiton/theme/tokens/AnalyticsStrings.kt), [EditorStrings](https://github.com/v1tzor/TimePlanner/blob/main/features/editor/impl/src/main/java/ru/aleshin/features/editor/impl/presentation/theme/tokens/EditorStrings.kt), [SettingsStrings](https://github.com/v1tzor/TimePlanner/blob/main/features/settings/impl/src/main/java/ru/aleshin/features/settings/impl/presentation/theme/tokens/SettingsStrings.kt), [TimePlannerStrings](https://github.com/v1tzor/TimePlanner/blob/main/core/ui/src/main/java/ru/aleshin/core/ui/theme/tokens/TimePlannerStrings.kt) These files contain lines for translation, if you want, you can download them and translate by analogy as it has already been done there.

**Comment by SirCrownguard** [comment]
I'm sorry I'm late. As a university student, I had exams to take care of. So I couldn't spare enough time for the translation.

I translated the files you showed me into Turkish. I did not add anything to the existing files. I only translate the English strings into Turkish and send you that part. I also added `trLanguageTitle = "Turkish"` to `SettingStrings.kt`, I thought you should know.

I'm looking forward to the update, and if you have other projects, I'd be happy to help you with those too.

[AnalyticsStrings.txt](https://github.com/v1tzor/TimePlanner/files/13476416/AnalyticsStrings.txt)
[EditorStrings.txt](https://github.com/v1tzor/TimePlanner/files/13476417/EditorStrings.txt)
[HomeStrings.txt](https://github.com/v1tzor/TimePlanner/files/13476418/HomeStrings.txt)
[SettingsStrings.txt](https://github.com/v1tzor/TimePlanner/files/13476419/SettingsStrings.txt)
[TimePlannerStrings.txt](https://github.com/v1tzor/TimePlanner/files/13476420/TimePlannerStrings.txt)
