### ISSUE TITLE
More options for notifications' alarms

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#65]
I would like to have many alarms options like "1 hour before", "1 day before", "as the event's time", "1 week before", "3 hours before", etc.

More than one alarm is selectable simultaneously. For example I can set "one day before" and "1 hour before". Both activated.

![1000095731](https://github.com/v1tzor/TimePlanner/assets/113377431/8ed68ebc-f804-437d-90dd-e23cf23a0ccc)

**Comment by v1tzor** [comment]
Done! I think I will release a new version of the application tomorrow
