### ISSUE TITLE
Agenda view: an overall sight over next 28 days' commitments

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#68]
Close the calendar button it would be useful an agenda button, in order to have an overal sight over the next 28 days' commitments (4 weeks). Basically TP has to show a commitments' list.

**Comment by v1tzor** [comment]
<table>
  <tr>
    <td valign="top"><img src="https://github.com/v1tzor/TimePlanner/assets/116388544/5fc98212-736d-4e6e-9551-515e4440d102" align="left" width="350dp"></td>
    <td valign="top"><img src="https://github.com/v1tzor/TimePlanner/assets/116388544/ff1746a8-5129-4e53-a92d-1579b795c4ba" align="center" width="350dp"></td>
  </tr>
 </table>

Now I am developing a screen for quick viewing of all schedules, and I have also added special non-distributed tasks with a deadline so that you can plan your schedule more conveniently later.

**Comment by v1tzor** [comment]
What do you think? Leave it like this?

**Comment by v1tzor** [comment]
> > What do you think? Leave it like this?
> 
> I would avoid side scrolling and open a new tab to show all the commitments in the next 28 days.
> 
> In my opinion you can leave those square tabs as long as they are four or five and do not start the side scrolling.
> 
> Maybe there you can put the next four engagements and the rest in a new tab?
> 
> What do you think? I seek order and immediacy, without sacrificing design.

OK, then I do 4-5 not scrolling schedules, and take the rest to another screen?

**Comment by v1tzor** [comment]
> I had an idea. What do you think if we move the calendar button to the bottom and the settings button above?
> 
> 
> 
> We have just to invent a common button for agenda and calendar and then switch between them when one is within of this tab.
> 
> 
> 
> Do you understand what I mean?
> 
> 
> 
> Settings tab is not pressed several times, so it can goes above.
> 
> Calendar/agenda button is often pushed, so it deserves a more comfortably position in the bottom tabs.
> 
> 
> 
> Let me know what is your position about this.
> 
> 
> 
> ![1000095863](https://github.com/v1tzor/TimePlanner/assets/113377431/32279711-fbda-4511-8259-ca30e4f5ac35)
> 
> 

Yes, I also thought about this option, most likely it will be more correct, I will try to implement it.

**Comment by v1tzor** [comment]
Done. However, I had to leave a button to open this screen in the top panel, but I think it's even better, you can try it yourself.
