### ISSUE TITLE
Почти будильник (предложение улучшения)

### ISSUE THREAD

**Issue by Wjxfi** [v1tzor/TimePlanner#7]
При начале события показывать Всплывающее Уведомление и/или Небольшой Звук и/или Мелодию Звонка. Всё это возможно будет выбрать или убрать в настройках, с помощью переключателя этих трех вещей. По умолчанию рекомендовано включить всё, кроме Мелодии Звонка.

это нужно чтобы не пропустить то, что хотел сделать. Я же не могу постоянно смотреть в приложение.

может помочь:

https://apt.izzysoft.de/fdroid/index/apk/com.bnyro.clock

https://www.f-droid.org/packages/com.github.axet.hourlyreminder/

https://apt.izzysoft.de/fdroid/index/apk/in.basulabs.shakealarmclock

https://www.f-droid.org/packages/com.better.alarm/

**Comment by v1tzor** [comment]
Пока было добавлено звуковое оповещение при начале задачи, спасибо за предложение
