### ISSUE TITLE
Rename category "Affairs" to "Chores"

### ISSUE THREAD

**Issue by Kevinf63** [v1tzor/TimePlanner#71]
Small and slightly silly suggested enhancement 😅 

Rename the default category "Affairs" to "Chores". Affairs is more formal English and while technically correct, unfortunately the word affair is often used as a shorthand for extramarital affairs in more casual modern English use.

**Comment by v1tzor** [comment]
> Small and slightly silly suggested enhancement 😅 
> 
> Rename the default category "Affairs" to "Chores". Affairs is more formal English and while technically correct, unfortunately the word affair is often used as a shorthand for extramarital affairs in more casual modern English use.

OK, in the next version of the app this will be changed :)
