### ISSUE TITLE
0.8.0 (27) Some boxes doesn't show properly the tasks numbers

### ISSUE THREAD

**Issue by serrq** [v1tzor/TimePlanner#79]
...due the large font of my phone 

![1000097243](https://github.com/v1tzor/TimePlanner/assets/113377431/156bb0ca-b96e-4a8b-b1b5-fe3f7436bd2e)

**Comment by v1tzor** [comment]
I have set a minimum size for information elements and reduced the possible distance between objects. Try downloading the [app](https://github.com/v1tzor/TimePlanner/releases/tag/0.8.0) again
