### ISSUE TITLE
возможность резервного копирования и восстановления данных (важно)

### ISSUE THREAD

**Issue by Wjxfi** [v1tzor/TimePlanner#8]
это абсолютно необходимо

я так старательно и долго создавал подкатегории и шаблоны, которые многочисленны, что я не хочу потерять их! А если я потеряю статистику, которая скоро будет, и историю, то будет жаль. Так что сделай это, пожалуйста

Может помочь:

https://apt.izzysoft.de/fdroid/index/apk/com.noto

https://www.f-droid.org/packages/io.github.quillpad/

https://www.f-droid.org/packages/com.omgodse.notally/

https://apt.izzysoft.de/fdroid/index/apk/com.yoshi.todark

https://www.f-droid.org/packages/com.nima.mymood/

**Comment by v1tzor** [comment]
Добавлено
