### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [v1tzor/TimePlanner#82]
ref: https://monitor.f-droid.org/builds/log/ru.aleshin.timeplanner/27#site-footer

Building locally to get the diff brb

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/7106361f6eb03109255a1861ac4e8e42b07e8353

**Comment by licaon-kter** [comment]
diff: [time27.log](https://github.com/v1tzor/TimePlanner/files/13334097/time27.log)

local APK built from tag commit eded1df4598f453298f7de774488e0cf8b681025 : 
[ru.aleshin.timeplanner_27.apk.ZIP](https://github.com/v1tzor/TimePlanner/files/13334147/ru.aleshin.timeplanner_27.apk.ZIP)

Seeing those `OverviewScheduleItem.kt` line differences and `EEE, MMM d` lines makes me think you built your APK from a different commit like b10b41f3097dabf461134f3ca9109abee498adca or something?

**Comment by v1tzor** [comment]
> diff: [time27.log](https://github.com/v1tzor/TimePlanner/files/13334097/time27.log)
> 
> 
> 
> local APK built from tag commit eded1df4598f453298f7de774488e0cf8b681025 : 
> 
> [ru.aleshin.timeplanner_27.apk.ZIP](https://github.com/v1tzor/TimePlanner/files/13334147/ru.aleshin.timeplanner_27.apk.ZIP) _(remove .ZIP)_
> 
> 
> 
> Seeing those `OverviewScheduleItem.kt` line differences and `EEE, MMM d` lines makes me think you built your APK from a different commit like b10b41f3097dabf461134f3ca9109abee498adca or something?
> 
> 
> 
> fyi @linsui

In gitlab, I tried to fix this problem, there I put the most recent comit on which the APK was built and it did nothing. I do not know what the problem may be. It originated on the previous version

**Comment by v1tzor** [comment]
Similar problem https://github.com/jellyfin/jellyfin-android/issues/414

**Comment by licaon-kter** [comment]
> Similar problem https://github.com/jellyfin/jellyfin-android/issues/414

You realize we have hundreds of "F-Droid can't build" opened issues, right? :smile:  that one does not look related :shrug: 

> In gitlab, I tried to fix this problem, there I put the most recent comit on which the APK was built and it did nothing.

Link ?

**Comment by licaon-kter** [comment]
Rebuilt from https://github.com/v1tzor/TimePlanner/commit/b10b41f3097dabf461134f3ca9109abee498adca but
```
Binary files /tmp/tmpu1k3t9yi/unsigned_binaries_ru.aleshin.timeplanner_27.binary/content/classes2.dex and /tmp/tmpu1k3t9yi/_tmp_tmpu1k3t9yi_sigcp_ru.aleshin.timeplanner_27/content/classes2.dex differ
Binary files /tmp/tmpu1k3t9yi/unsigned_binaries_ru.aleshin.timeplanner_27.binary/content/res/BI.png and /tmp/tmpu1k3t9yi/_tmp_tmpu1k3t9yi_sigcp_ru.aleshin.timeplanner_27/content/res/BI.png differ
```

Can you try to clean up eg. gradle and other stuff that accumulates and create an APK from https://github.com/v1tzor/TimePlanner/commit/b10b41f3097dabf461134f3ca9109abee498adca again?

**Comment by v1tzor** [comment]
> Rebuilt from [b10b41f](https://github.com/v1tzor/TimePlanner/commit/b10b41f3097dabf461134f3ca9109abee498adca) but
> 
> ```
> Binary files /tmp/tmpu1k3t9yi/unsigned_binaries_ru.aleshin.timeplanner_27.binary/content/classes2.dex and /tmp/tmpu1k3t9yi/_tmp_tmpu1k3t9yi_sigcp_ru.aleshin.timeplanner_27/content/classes2.dex differ
> Binary files /tmp/tmpu1k3t9yi/unsigned_binaries_ru.aleshin.timeplanner_27.binary/content/res/BI.png and /tmp/tmpu1k3t9yi/_tmp_tmpu1k3t9yi_sigcp_ru.aleshin.timeplanner_27/content/res/BI.png differ
> ```
> 
> Can you try to clean up eg. gradle and other stuff that accumulates and create an APK from [b10b41f](https://github.com/v1tzor/TimePlanner/commit/b10b41f3097dabf461134f3ca9109abee498adca) again?

Done. I have updated the apk

**Comment by v1tzor** [comment]
I managed to solve this problem🎉, need to update the commit to (last): 811db0ed8870923c4d36843c7b4d4c585e02f458. [Pipeline](https://gitlab.com/v1tz0r/fdroiddata/-/jobs/5554753672) successfully builds a project with it. You will be able to upgrade .yml, or I make a pull request in gitlab? @licaon-kter
