### ISSUE TITLE
F-Droid listing

### ISSUE THREAD

**Issue by IzzySoft** [v1tzor/TimePlanner#84]
First congrats to your listing at F-Droid.org! At this time I'd remove the app from my repo. But as you still carry my badge on the Readme, that would cause some confusion due to the "404 page not found" then. What are your plans there? A "double listing"?

**Comment by v1tzor** [comment]
> First congrats to your listing at F-Droid.org! At this time I'd remove the app from my repo. But as you still carry my badge on the Readme, that would cause some confusion due to the "404 page not found" then. What are your plans there? A "double listing"?

The badge has now been removed

**Comment by IzzySoft** [comment]
Thanks! Will remove the app here then. Should for any reason you need it back, just "ring my bell". Metadata is just archived, so re-listing is easy. All the best for you!

**Comment by v1tzor** [comment]
> Thanks! Will remove the app here then. Should for any reason you need it back, just "ring my bell". Metadata is just archived, so re-listing is easy. All the best for you!

Ok, thanks you very much)
