### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by groeable** [v1tzor/TimePlanner#91]
Is there gonna be more lanhuages? Is there option to help with translations?

**Comment by v1tzor** [comment]
> Is there gonna be more lanhuages? Is there option to help with translations?

I will be very grateful to you 
for the translation. It will be enough for me if you just add lines by example as it has already been done. Files for translation: [HomeStrings](https://github.com/v1tzor/TimePlanner/blob/main/features/home/impl/src/main/java/ru/aleshin/features/home/impl/presentation/theme/tokens/HomeStrings.kt#L24C8-L24C8), [AnalyticsStrings](https://github.com/v1tzor/TimePlanner/blob/main/features/analytics/impl/src/main/java/ru/aleshin/features/analytics/impl/presenatiton/theme/tokens/AnalyticsStrings.kt), [EditorStrings](https://github.com/v1tzor/TimePlanner/blob/main/features/editor/impl/src/main/java/ru/aleshin/features/editor/impl/presentation/theme/tokens/EditorStrings.kt), [SettingsStrings](https://github.com/v1tzor/TimePlanner/blob/main/features/settings/impl/src/main/java/ru/aleshin/features/settings/impl/presentation/theme/tokens/SettingsStrings.kt), [TimePlannerStrings](https://github.com/v1tzor/TimePlanner/blob/main/core/ui/src/main/java/ru/aleshin/core/ui/theme/tokens/TimePlannerStrings.kt)
