### ISSUE TITLE
Please an howto for shedule fonction

### ISSUE THREAD

**Issue by esalaud** [v1tzor/TimePlanner#95]
Hello,
I really like your application, but I don't fully understand the pattern + repeat function.
It would be cool if you could make a short demonstration video on YouTube.
Have a nice day.

**Comment by Rafee-M** [comment]
I think #54 should answer your question

**Comment by esalaud** [comment]
Thank you so much !

Le 4 janvier 2024 01:49:55 GMT+01:00, Raf ***@***.***> a écrit :

**Comment by v1tzor** [comment]
> Hello, I really like your application, but I don't fully understand the pattern + repeat function. It would be cool if you could make a short demonstration video on YouTube. Have a nice day.

Thanks for the feedback, sorry that I haven't been in touch with you for a long time, I took a break :), I'm closing the issue now, if you still need help, write
