### ISSUE TITLE
Ability to choose a duration with no start / end time

### ISSUE THREAD

**Issue by Zeit08** [v1tzor/TimePlanner#97]
Hi. Your app is great, I was looking for an app that can keep track of my different job tasks during the day.

I wanted to divide them in timeslots, but without a start time and end time constraints.

Example:

15min of news read 
30 min of writing
2 hours of coding
1 hour of consulting
30min video analysis

So these activities are more or less the same each day, and I would like to take the phone, select an activity and press start. So when the time runs out I am done with that activity and I can select another one.

At the end of the day I check if I have completed all the activities.

Maybe is more like a habit tracker and it's not the purpose of your app?

**Comment by ravihlb** [comment]
Hi! Happy new year :)

Have you tried [Goodtime](https://github.com/adrcotfas/Goodtime) yet? It's a very minimalist pomodoro-style timer in which you can setup different timer presets as well as different labels, if you want. I use it pretty much everyday and it sounds to me like it would serve your purposes well.
